# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: __underscore
author: underscore
email:
description: > # this means to ignore newlines until "baseurl:"
  __underscore is the blog of Jake Underscore. Expect: philosophy, post-punk, popular culture, politics, etc.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.underscoreblog.com" # the base hostname & protocol for your site
twitter_username: jake_underscore
github_username:
title_image: "https://www.underscoreblog.com/assets/img/Ulogo_sq.jpg"

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics:
disqus_shortname: underscore1

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
